[package]
name = "loan_calculator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
wasm-bindgen = "0.2.100"
serde-wasm-bindgen = "0.6"
